### ISSUE TITLE
some parameters meaning

### ISSUE THREAD

**Issue by supengufo** [VincentCheungM/Run_based_segmentation#16]
兄台，打扰您一下，请问以下这段代码的几个数是什么意思？
包括：
1、0.00279111
2、563
3、1688
`range = sqrt(point.x*point.x + point.y*point.y + point.z*point.z);
            if (point.x >= 0) {
                row = int(563 - asin(point.y/range)/0.00279111);
            }
            else if (point.x < 0 && point.y <= 0) {
                row = int(1688 + asin(point.y/range)/0.00279111);
            }
            else {
                row = int(1688 + asin(point.y/range)/0.00279111);
            }`

不胜感激！

**Comment by VincentCheungM** [comment]
Sorry for so many magic numbers. But I don't have time for these rbs now. 
If my memory serves me right, the `row` should be `column` more precisely.  It's mainly arrange points into tensor like depth images here. 

Here comes the specific magic value in  this case : 

Velodyne HDL-32E sampled 10Hz-600RPM
The `0.0027911` is the radian of `0.16` which is the horizontal resolution for HDL-32E 600RPM, refereed to [HDL-32E Mannual](https://www.argocorp.com/cam/special/Velodyne/common/pdf/63-9113%20HDL-32E%20manual_Rev%20C_FEB2012%20web.pdf).
And respectively `563` and `1688` should be the index of column like `1/2 pi` or `3/2 pi`.

**Comment by supengufo** [comment]
sorry,my chinese words pull down your issue aera high style~ :)
thank you very much for your reply!
your work is really good!
the only question is that the SLR calculate too many clusters in a frame,and most of the clusters' size is between 0 to 5. So i think if you can add a threshold parameter to reduce the clusters' size,the algorithm will be better!
