### ISSUE TITLE
Couldn't find code for segments N segs - Ground Pane Fitting ?

### ISSUE THREAD

**Issue by SakthiGs** [VincentCheungM/Run_based_segmentation#4]
Hi,

Thanks for the code. it works really well, little lagging in real time performance.
Couldn't find the code for segments "N segs", Can you share the update code with N Segs which you have implemented

**Comment by VincentCheungM** [comment]
Hi @SakthiGs, sorry for replying you so late. I think that it's quite easy for you to get it done by applying a few pass-through filters and then applying the so called GPF on each sub point cloud. As this is only some toy codes for a paper, I'm going to make so much configuration for that. I believe you could get it done by your self, and hopefully you could make a PR if necessary.

**Comment by kxhit** [comment]
I noticed this too. Have anyone done? Thanks!
