### ISSUE TITLE
clustering results lose part of non-ground points?

### ISSUE THREAD

**Issue by SJingjia** [VincentCheungM/Run_based_segmentation#9]
Hi VincentCheungM,Thanks for your fantastic work!
I run the codes with KITTI dataset, and the following figure shows all the non-ground points(different colors represent different rings):
![image](https://user-images.githubusercontent.com/28842290/53697160-7f20e200-3e09-11e9-8d29-1c39cd5189d1.png)
But after clustering, some of them are missing:
![image](https://user-images.githubusercontent.com/28842290/53697176-95c73900-3e09-11e9-8a50-c7329009d586.png)
do you have any idea? Is it because the parameters need to be adjusted ?
Thank you very much and looking forward to your reply.

**Comment by VincentCheungM** [comment]
Sorry for replying you late. It seems that I use some kind of trick before the clustering process. I just simply re-organize all the spare point cloud into `matrix`-like dense format, e.g.:
 I've got points {p1, p2, p3} from LiDAR, and I transform them from (x, y, z) into Sphere coordinates (\theta, \phi). And then it could be some 2D matrix like data. In this case, some items in the matrix are not occupied, i.e., none of points from point cloud P is transform into this (\theta_hat, \phi_hat), so I use the `intensity` property to mark these items are not occupied and not interested.  







------------------ Original ------------------
